# Setup
title:        Fyrd
tagline:      "A Python Cluster: Submit functions and shell scripts to torque, slurm, or local machines using easy python syntax."
favicon:      "/assets/logo/favicon"
version:      "0.6.1-beta.6"
csshighlight: default

# License
license:
  name:     'MIT'
  url:      "https://github.com/MikeDacre/fyrd/blob/master/LICENSE"

# About/contact
author:
  name:     Michael Dacre
  url:      https://www.michaeldacre.com

# GitHub
github:
  repository_url:  "https://github.com/MikeDacre/fyrd"
  url:             "/fyrd"
  api_url:         "https://api.github.com"
 
# Gems
gems:
  - kramdown
  - jekyll-cayman-theme
  - jekyll-github-metadata

#Others
markdown: kramdown
theme: jekyll-cayman-theme
highlighter: rouge

kramdown:
  input: GFM
  syntax-highlighter: rouge
