# Setup
title:        Fyrd
tagline:      "A Python Cluster: Submit functions and shell scripts to torque, slurm, or local machines using easy python syntax."
description:  "Submit functions and shell scripts to torque, slurm, or local machines using easy python syntax."
version:      "0.6.1b9"
baseurl:      "https://fyrd.science"
csshighlight: default

# License
license:
  name:     'MIT'
  url:      "https://github.com/MikeDacre/fyrd/blob/master/LICENSE"

# About/contact
author:
  name:     Mike Dacre
  url:      https://www.michaeldacre.com

# GitHub
github:
  repository_url:  "https://github.com/MikeDacre/fyrd"
  url:             "https://fyrd.science"
  # url:             "/fyrd"
 
# Gems
gems:
  - kramdown
  - jekyll-github-metadata
  # - jekyll-cayman-theme
  # - jekyll-sitemap

#Others
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax-highlighter: rouge
